language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kllee-au/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kllee-au/docker-react npm run test

deploy: 
  provider: azure_web_apps
  username: docker-react2
  password: docker-react2
  site: docker-react2